require("settings")
require("mappings")
require("plugins")

require("plugins.rose-pine")
require("plugins.uuid-plugin")

require("plugins.dap")
require("dapui").setup()
require("plugins.harpoon")
require("plugins.fidget")
require("plugins.nvim-lint")
require("plugins.lualine")
require("plugins.signature-help")
require("plugins.worktrees")
require("plugins.catpuccino")
